### ISSUE TITLE
Develop/design keyboard input

### ISSUE THREAD

**Issue by aaronlael** [Nhawdge/maxyph#10]
QWERTY input buttons at the bottom of the gamespace that drive the input to the play space rather than actual key presses.  This ensures that the active box is correct and helps make the game more platform agnostic (and familiar looking).

The keys should default to all starting as a single color aside from the initially placed letter in the initial game state, which should be a lighter/different shade to indicate that it has been used in the puzzle (this helps provide player feedback for scoring).

Once a letter is "locked out" and cannot be used further, it should be indicated on the keyboard.  I would prefer to use a texture rather than a color for this so that it can be more accessible, like stripes, or an slash through it.

**Comment by Nhawdge** [comment]
![image](https://github.com/Nhawdge/maxyph/assets/14846019/55f4275b-4dc5-4ab7-a61c-8cc8f70a0a82)

**Comment by aaronlael** [comment]
![image](https://github.com/Nhawdge/maxyph/assets/32605887/9ee7caf7-b829-4752-9343-fabecd567f81)

**Comment by Nhawdge** [comment]
I think this is done.

**Comment by aaronlael** [comment]
@Nhawdge even out the back and the enter key, and change the back key functionality to just "delete" instead of back, then delete on second press.  double press on mobile leads to unintended zooming.

**Comment by Nhawdge** [comment]
I'm closing this.
