### ISSUE TITLE
Change Ko-Fi logo to provided widget link.

### ISSUE THREAD

**Issue by aaronlael** [Nhawdge/maxyph#11]
<script src='https://storage.ko-fi.com/cdn/scripts/overlay-widget.js'></script>
<script>
  kofiWidgetOverlay.draw('maxyph', {
    'type': 'floating-chat',
    'floating-chat.donateButton.text': 'Support me',
    'floating-chat.donateButton.background-color': '#fcbf47',
    'floating-chat.donateButton.text-color': '#323842'
  });
</script>

**Comment by Nhawdge** [comment]
Finally fixed.
