### ISSUE TITLE
Change Puzzle Layout to Diamond Boxes

### ISSUE THREAD

**Issue by aaronlael** [Nhawdge/maxyph#3]
![image](https://github.com/Nhawdge/maxyph/assets/32605887/8d8f77b9-96b5-4af2-92e7-614b59a2b360)

We talked about this on discord.  This is a key differentiator from other puzzle games in the "space."

I think there will need to be a shadow to highlight the active row and some kind of helper color or something to show what letter will move to the next row.

**Comment by aaronlael** [comment]
UI reference from MS Paint (like a professional would provide)
![image](https://github.com/Nhawdge/maxyph/assets/32605887/391fc86e-5f40-4680-b2ca-30d62c6b50e6)

**Comment by aaronlael** [comment]
do the thing @Nhawdge

**Comment by Nhawdge** [comment]
I think this is done

**Comment by aaronlael** [comment]
it is.  weehoo
