### ISSUE TITLE
Implement letter restriction

### ISSUE THREAD

**Issue by aaronlael** [Nhawdge/maxyph#5]
The game should not allow you to select an "orange-boxed" letter from a previous row.  At the end of the puzzle, this means that there will be a maximum of 5 letters that are "locked" from the user for their last word choice.  Clever players may be able to have less by using strategically placed duplicate letters in words.

These letters should visually and mechanically be locked out from the input keyboard.

As an example, where a user is populating the 3rd row:
![image](https://github.com/Nhawdge/maxyph/assets/32605887/385fccae-1e6a-4f3f-9cef-8df7c8a6c9fe)
The user may not use the letters "O" or "A" but they can use "N" multiple times if they desire to as it is the current row.

If a user manages to drop a locked value down a row due to strategic use of multiple instances of the same character in a word that causes it to drop down to the next row, it is locked and cannot be used in the current row aside from the orange box.

**Comment by aaronlael** [comment]
![image](https://github.com/Nhawdge/maxyph/assets/32605887/beb64e24-e72a-4c78-b41f-acaab61964af)
re-adding screenshot without transparency

**Comment by Nhawdge** [comment]
I think this is done

**Comment by aaronlael** [comment]
it is.  you did good @Nhawdge
